frontendでコンパイルエラーが起きてyarn buildできない件を解消 (#8)
* ./components/calender/WeekCalender/CalenderMenu.tsx:12:6 Type error: Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes'.

* components/calender/calenderComponents/Calender/index.tsx:124:13 - error TS2322: Type 'number | MutableRefObject<htmldivelement>' is not assignable to type ~

* components/dish/DishForm/DishForm/DishFormOfOnlyDishFields.tsx:47:57 - error TS2339: Property 'name' does not exist on type 'FieldError | Merge<FieldError, FieldErrorsImpl<any>>'.

* components/dish/DishForm/DishForm/DishFormOfRelatedDishSource.tsx:19:62 - error TS1016: A required parameter cannot follow an optional parameter.

* components/dish/DishForm/DishForm/DishSourceFormRelationContent.tsx:77:39 - error TS2339: Property 'recipeBookPage' does not exist on type '{}'.

* 不要なテストを削除

* components/dish/Source/SourceForm/SourceForm.tsx:45:63 - error TS2339: Property 'name' does not exist on type 'FieldError | Merge<FieldError, FieldErrorsImpl<any>>'.

* components/meal/MealForm/MealForm/ExistingDishesForRegisteringWithMeal.tsx:99:28 - error TS2322: Type 'string | FieldError | Merge<FieldError, FieldErrorsImpl<any>>' is not assignable to type 'string'.

* components/meal/MealForm/MealForm/index.tsx:92:61 - error TS2339: Property 'date' does not exist on type 'FieldError | Merge<FieldError, FieldErrorsImpl<any>>'.

* features/auth/loginMutation.ts:29:7 - error TS2322: Type '{ email?: string; password?: string; }' is not assignable to type 'Exact<{ email: string; password: string; }>'.

* features/auth/signUpMutation.ts:47:7 - error TS2322: Type '{ email?: string; password?: string; passwordConfirmation?: string; }' is not assignable to type 'Exact<{ email: string; password: string; passwordConfirmation: string; }>'.

* pages/_app.tsx:25:8 - error TS2786: 'Component' cannot be used as a JSX component.

* pages/admin/dish/word/normalize.tsx:1:1 - error TS1208: 'normalize.tsx' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.