components/dish/DishForm/DishForm/DishFormOfOnlyDishFields.tsx:47:57 - error TS2339: Property 'name' does not exist on type 'FieldError | Merge<FieldError, FieldErrorsImpl<any>>'.