pages/admin/dish/word/normalize.tsx:1:1 - error TS1208: 'normalize.tsx' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.